### ISSUE TITLE
Is this addon working?

### ISSUE THREAD

**Issue by Spunkette** [Natherul/AutoClearMark-wow-addon#1]
Hi. I have this installed, but I am still bombarded by idiotic orange circles on me when I tank or stars on me when I heal. I have been in groups with people using Deja Auto Mark and it does not seem to remove them. No idea what the addon is that marks with circle/star.

**Comment by Natherul** [comment]
Sorry, I had a break from wow.

I have updated the addon today and tested it myself. Now it will automatically enable itself on load (instead of having to /dam on, and it triggers on entering and leaving combat)

**Comment by Spunkette** [comment]
Awesome thank you! I loo forward to seeing it work.
